### PR TITLE
Pygtk3

### PR DESCRIPTION
**Pull request by gbm19**
This PR moves Revelation from Python2/pygtk2 to Python3/PyGObject

Tested on Fedora32 with: python-3.8.2, python3-gobject-3.36,   python3-dbus-1.2.16, python3-pwquality-1.4.2, python3-crypto-2.6.1
Tested on Fedora30 with: python-3.7.7, python3-gobject-3.32.2, python3-dbus-1.2.8,  python3-pwquality-1.4.0, python3-crypto-2.6.1

How to test it in your system:
#% get the code
git clone ...

#% compile gsettings schema
glib-compile-schemas src/data/schemas

#% add icons
sudo cp -pv src/data/icons/scalable/*.svg /usr/share/icons/hicolor/scalable/apps/
sudo gtk-update-icon-cache /usr/share/icons/hicolor

#% add translation for language 'll', locale 'll_CC'
mkdir -p src/data/locale/ll_CC/LC_MESSAGES
msgfmt po/ll.po -o src/data/locale/ll_CC/LC_MESSAGES/revelation.mo

#% run Revelation
LC_ALL=ll_CC ./src/revelation.py

### CODE REVIEW

**Comment by mikelolasagasti** [comment]
@gbm19 awesome job! 😍

I'm reviewing the code changes and it looks very good. I'll need some days to test it, but I'll try to provide feedback during this week.

**Comment by gbm19** [comment]
Thanks! No need to hurry. As it is now, it is already useful for me.

Missatge de Mikel Olasagasti Uranga <notifications@github.com> del dia dl.,
3 d’ag. 2020 a les 20:52:

**Comment by mhmoran** [comment]
I'd be willing to test on Linux Mint 20 .. just need some help with system setup as I'm not familiar with  the setup for 

      #% compile gsettings schema
      glib-compile-schemas src/data/schemas

Tried but fails with the directory missing error

**Comment by gbm19** [comment]
You need to 'cd'  into the cloned git working path.


Missatge de Mike Moran <notifications@github.com> del dia dt., 4 d’ag. 2020
a les 2:08:

**Comment by mikelolasagasti** [comment]
@gbm19 I merged most of the patches to a branch called `devel`. I'll keep the PR open, as there are some fixes missing, until I merge all the patches related to the code. I can't merge it completely as some of the commits, like the path changes require build system changes and I don' think they're required.

**Comment by mhmoran** [comment]
Apparently, I've done something wrong with Git .. as there is not a src/data in
the path where I cloned the repo to .

Sent from [ProtonMail](https://protonmail.com), Swiss-based encrypted email.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mikelolasagasti** [comment]
Closing this PR as new release with most of the work has been released. Huge thanks @gbm19 !

**Pull request closed without merging**
